# Configuration file for TrainDepartures
# Use to add your own home station and platforms

stations:
  - { code: SOU, platform: 1 }
  - { code: WAT, platform: 4 }

# Width of departure boards. Minimum is 48
board_width: 60
additional_services: 5