# Configuration file for TrainDepartures
# Use to add your own home station_name and platforms

stations:
  - { code: SOU, platform: 1 }
  - { code: SOU, platform: 4 }
  - { code: STP, platform: A }

# Width of departure boards. Minimum is 48
board_width: 60
additional_services: 5